Kidal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from ExamenApp import views as ExamenApp_views
from KidalApp import views as kidal_views

urlpatterns = [
        path('grappelli/', include('grappelli.urls')),  # Ajouter l'URL de Grappelli ici
    path('admin/', admin.site.urls),
        path('dashboard/', kidal_views.dashboard, name='dashboard'),

    path('', include('KidalApp.urls')),
    


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


KidalApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import dashboard

urlpatterns = [
    path('', views.accueil, name='accueil'),
        path('produit/', views.produit, name='produit'),
                path('about/', views.about, name='about'),
                                path('contact/', views.contact, name='contact'),
 path('recherche/', views.rechercher_produit, name='recherche_produit'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('commander/<int:produit_id>/', views.commander_produit, name='commander_produit'), # Ajoutez ce chemin pour la commande du produit
    path('confirmation_commande/<int:commande_id>/', views.confirmation_commande, name='confirmation_commande'),
    path('contactez-nous/', views.contactez_nous, name='contactez_nous'),
    path('conf/', views.conf, name='conf'),
    path('facture/<int:commande_id>/', views.generate_invoice_pdf, name='generate_invoice_pdf'),
  path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
path('panier/', views.gerer_panier, name='gerer_panier'),
    path('commander_panier/', views.commander_panier, name='commander_panier'),
    path('confirmationn_commande/<int:commande_id>/', views.confirmationn_commande, name='confirmationn_commande'),
    path('ajouter-au-panier/<int:produit_id>/', views.ajouter_au_panier, name='ajouter_au_panier'),
    path('admin/dashboard/', dashboard, name='dashboard'),


]

KidalApp/models.py
from datetime import datetime
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db import models

class Categorie(models.Model):
    nom = models.CharField(max_length=100)

    def __str__(self):
        return self.nom

class Produit(models.Model):
    nom = models.CharField(max_length=100)
    description = models.TextField()
    prix = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='produits/', null=True, blank=True)

    def __str__(self):
        return self.nom


    def __str__(self):
        return self.nom

class Commande(models.Model):
    MODE_PAIEMENT_CHOICES = [
        ('1', 'Paiement par carte'),
        ('2', 'Paiement par orange money'),
        ('3', 'Paiement sur place une fois livré'),
    ]

    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    utilisateur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    quantite = models.PositiveIntegerField(default=1)
    mode_paiement = models.CharField(max_length=255, choices=MODE_PAIEMENT_CHOICES)
    date_commande = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f"Commande de {self.produit} par {self.utilisateur if self.utilisateur else 'un utilisateur non connecté'}"

    def save(self, *args, **kwargs):
        if self.produit.stock >= self.quantite:
            super().save(*args, **kwargs)
            self.produit.stock -= self.quantite
            self.produit.save()
        else:
            raise ValueError("Le produit est en rupture de stock.")

class CustomUser(AbstractUser):
    adresse = models.CharField(max_length=100, blank=True)

class Message(models.Model):
    utilisateur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contenu = models.TextField()
    date_envoi = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message de {self.utilisateur.username} envoyé le {self.date_envoi}"


# models.py

from django.db import models
from django.conf import settings

class Panier(models.Model):
    utilisateur = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Panier de {self.utilisateur.username}"

    def total_price(self):
        total = 0
        for item in self.items.all():
            total += item.total_price()
        return total


class PanierItem(models.Model):
    panier = models.ForeignKey(Panier, on_delete=models.CASCADE, related_name='items')
    produit = models.ForeignKey('Produit', on_delete=models.CASCADE)
    quantite = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.produit.nom} x {self.quantite} dans le panier de {self.panier.utilisateur.username}"

    def total_price(self):
        return self.produit.prix * self.quantite


class CommanderPanier(models.Model):
    MODE_PAIEMENT_CHOICES = [
        ('1', 'Paiement par carte'),
        ('2', 'Paiement par orange money'),
        ('3', 'Paiement sur place une fois livré'),
    ]

    panier = models.ForeignKey(Panier, on_delete=models.CASCADE, related_name='commandes')
    utilisateur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    mode_paiement = models.CharField(max_length=255, choices=MODE_PAIEMENT_CHOICES)
    date_commande = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Commande pour {self.panier.utilisateur.username} - {self.date_commande}"

KidalApp/forms.py
# Dans KidalApp/forms.py

from django import forms

class MessageForm(forms.Form):
    message = forms.CharField(label='Votre message', widget=forms.Textarea(attrs={'rows': 4}))
from django import forms
from .models import CustomUser

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password', 'adresse']


KidalApp/templates/KidalApp/views.py
from django.shortcuts import render

# Create your views here.
from .models import *
# Create your views here.
def accueil(request):
    return render(request, 'KidalApp/accueil.html')


from django.contrib.auth.decorators import login_required


def produit(request):
    produits = Produit.objects.all()
    return render(request, 'KidalApp/produit.html', {'produits': produits})




def rechercher_produit(request):
    if 'q' in request.GET:
        query = request.GET['q']
        produits = Produit.objects.filter(nom__icontains=query)
    else:
        produits = Produit.objects.all()
    return render(request, 'KidalApp/rechercher_produit.html', {'produits': produits})




from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login


from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Produit, Panier, Commande, Message
from .forms import RegisterForm

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login  # Ajoutez ceci
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Produit, Panier, CustomUser
from .forms import RegisterForm
from django.contrib.auth import authenticate, login
from django.contrib import messages

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('accueil')
        else:
            messages.error(request, 'Nom d\'utilisateur ou mot de passe incorrect.')
            return render(request, 'KidalApp/login.html', {'error_message': 'Nom d\'utilisateur ou mot de passe incorrect.'})
    else:
        return render(request, 'KidalApp/login.html')



from django.contrib.auth import logout

def logout_user(request):
    logout(request)
    return redirect('accueil')

from django.contrib.auth import login
from .forms import RegisterForm
from django.contrib.auth.models import User

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])  # Utilisez set_password pour sécuriser le mot de passe
            user.save()
            login(request, user)  # Connectez automatiquement l'utilisateur après l'inscription
            messages.success(request, 'Vous êtes maintenant inscrit.')
            return redirect('accueil')
    else:
        form = RegisterForm()
    return render(request, 'KidalApp/register.html', {'form': form})



from django.shortcuts import redirect
from .models import Produit, Panier


from .models import Panier

def panier(request):
    if request.user.is_authenticated:
        panier = Panier.objects.get_or_create(utilisateur=request.user)[0]
        produits = panier.produits.all()
        return render(request, 'KidalApp/panier.html', {'produits': produits})
    else:
        return redirect('login')  # Redirigez l'utilisateur vers la page de connexion s'il n'est pas connecté


from django.shortcuts import render, redirect
from .models import Panier, Produit
from django.shortcuts import render, redirect
from .models import Panier, Produit
def ajouter_au_panier(request):
    if request.method == 'POST':
        produit_id = request.POST.get('produit_id')
        quantite = int(request.POST.get('quantite', 1))  # Ajout de la quantité
        produit = Produit.objects.get(pk=produit_id)
        if request.user.is_authenticated:
            panier, created = Panier.objects.get_or_create(utilisateur=request.user)
            panier.produits.add(produit, through_defaults={'quantite': quantite})  # Ajout de la quantité
            return redirect('panier')
        else:
            return redirect('login')
    else:
        return redirect('accueil')


from django.shortcuts import redirect
from .models import Panier

def supprimer_panier(request):
    if request.user.is_authenticated:
        # Récupérer le panier de l'utilisateur s'il existe
        panier = Panier.objects.filter(utilisateur=request.user).first()
        if panier:
            # Supprimer le panier
            panier.delete()
    # Rediriger l'utilisateur vers une page après la suppression du panier
    return redirect('accueil')  # Rediriger vers la page d'accueil par exemple


def confirmation_commande(request):
    return render(request, 'KidalApp/confirmation_commande.html')

from django.shortcuts import render, redirect
from .models import Produit, Commande
from django.contrib import messages
def commander_produit(request, produit_id):
    if request.method == 'POST':
        quantite = int(request.POST.get('quantite', 1))
        mode_paiement = int(request.POST.get('mode_paiement', 1))  # Récupérer le mode de paiement sélectionné
        produit = Produit.objects.get(id=produit_id)

        # Vérifier si le produit est disponible en quantité suffisante
        if produit.stock >= quantite:
            # Créer une commande
            commande = Commande.objects.create(
                produit=produit,
                utilisateur=request.user if request.user.is_authenticated else None,
                quantite=quantite
            )

            # Réduire le stock du produit
            produit.stock -= quantite
            produit.save()

            messages.success(request, 'Votre commande a été passée avec succès!')
            return redirect('confirmation_commande')  # Rediriger l'utilisateur vers le panier

        else:
            messages.error(request, 'Le produit est en rupture de stock.')
            return redirect('produit')  # Rediriger l'utilisateur vers la liste des produits

    # Si la méthode HTTP n'est pas POST, afficher le formulaire de commande
    produit = Produit.objects.get(id=produit_id)
    return render(request, 'KidalApp/commande.html', {'produit': produit})


def conf(request):
    return render(request, 'KidalApp/conf.html')
@login_required
def contactez_nous(request):
    if request.method == 'POST':
        contenu = request.POST.get('contenu', '')
        if contenu:
            message = Message.objects.create(utilisateur=request.user, contenu=contenu)
            message.save()
            return redirect('conf')  # Rediriger vers la page d'accueil après l'envoi du message
    return render(request, 'KidalApp/contactez_nous.html')

def conf(request):
    return render(request, 'KidalApp/conf.html')


def my_page(request):
    return render(request, 'histoire.html')

KidalApp/templates/KidalApp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Sahel Gomme</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  {% load static %}

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- =======================================================
  * Template Name: EstateAgency
  * Template URL: https://bootstrapmade.com/real-estate-agency-bootstrap-template/
  * Updated: Mar 17 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
<!-- ======= Property Search Section ======= -->
<div class="click-closed"></div>
<!--/ Form Search Star /-->
<div class="box-collapse">
  <div class="title-box-d">
    <h3 class="title-d">Rechercher</h3>
  </div>
  <span class="close-box-collapse right-boxed bi bi-x"></span>
  <div class="box-collapse-wrap form">
    <form class="form-a" method="get" action="{% url 'recherche_produit' %}">
      <div class="row">
        <!-- Section ajoutée pour la recherche de produit -->
        <div class="col-md-12 mb-2">
          <div class="form-group">
            <label class="pb-2" for="search">Rechercher un produit</label>
            <input type="search" class="form-control form-control-lg form-control-a" placeholder="saisir le type de gomme arabique rechercher" aria-label="Search" name="q">
          </div>
        </div>
        <div class="col-md-12">
          <button type="submit" class="btn btn-b">Rechercher</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- End Property Search Section -->



  <!-- ======= Header/Navbar ======= -->
  <nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
    <div class="container">
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a class="navbar-brand text-brand" href="{% url 'accueil' %}">SAHEL <span
          class="color-b">GOMME
        </span></a>
          

      <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link  " href="{% url 'accueil' %}">Accueil</a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'about' %}">A propos de nous</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'produit' %}">Produits</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">User</a>
            <div class="dropdown-menu">
              <a class="dropdown-item " href=""> <span class="nav-link">Bonjour, {{ user.username }}</span>
              </a>
              <a class="dropdown-item" href="{% url 'gerer_panier' %}">
                <i class="fa fa-shopping-cart"></i>
                Panier
            </a>
              <a class="dropdown-item " href="{% url 'contactez_nous' %}">Contactez-nous</a>
              <a class="dropdown-item " href="{% url 'logout' %}">Déconnexion</a>
            </div>
          </li>

        </ul>
      </div>

      <button type="button" class="btn btn-b-n navbar-toggle-box navbar-toggle-box-collapse" data-bs-toggle="collapse"
        data-bs-target="#navbarTogglerDemo01">
        <i class="bi bi-search"></i>
      </button>


      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Connexion</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Inscription</a>
      </li>
      {% endif %}


    </div>
  </nav><!-- End Header/Navbar -->


  <!-- Votre contenu ici -->
  {% block content %}
  {% endblock %}




  <!-- ======= Footer ======= -->
  <section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">SahelGomme</h3>
            </div>
            <div class="w-body-a">
              <p class="w-text-a color-text-a">
                Une distribution de gomme arabique sur 
                toute l'etendue du territoire nationale.
              </p>
            </div>
            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  <span class="color-text-a">Phone .</span> +223 83 45 15 13
                </li>
                <li class="color-a">
                  <span class="color-text-a">Phone .</span> +223 70 92 70 96
                </li>
                <li class="color-a">
                  <span class="color-text-a">Phone .</span> +223 70 16 84 24
                </li>


                <li class="color-a">
                  <span class="color-text-a">Email .</span>SahelGomme@gmail.com
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">Notre societe</h3>
            </div>
            <div class="w-body-a">
              <div class="w-body-a">
                <ul class="list-unstyled">
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="{% url 'about' %}">A Propos De Nous</a>
                  </li>
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="{% url 'about' %}">Les Agents De <br>
                      Sahel Gomme</a>
                  </li>
              
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">Notre localite</h3>
            </div>
            <div class="w-body-a">
              <ul class="list-unstyled">
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">Bamako,</a>
                </li>
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">Mali</a>
                </li>
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">Sebenikoro</a>
                </li>

              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="nav-footer">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">Accueil</a>
              </li>

              <li class="list-inline-item">
                <a href="#"></a>
              </li>
              <li class="list-inline-item">
                <a href="#">A propos de nous</a>
              </li>
            </ul>
          </nav>
          <div class="socials-a">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-facebook" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-twitter" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-instagram" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-linkedin" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="copyright-footer">
            <p class="copyright color-text-a">
              &copy; Copyright
              <span class="color-a">SahelGomme</span> Tout droit Reserve.
            </p>
          </div>
          <div class="credits">
            <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=EstateAgency
          -->
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->

  <script src=" {% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src=" {% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src=" {% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>



  
</body>

</html>

KidalApp/templates/KidalApp/commander_panier.html
<!-- commander_panier.html -->

{% extends "KidalApp/base.html" %}
{% load static %}

{% block content %}

<main id="main">

  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">Commander le Panier</h1>
            <span class="color-text-a">Finaliser votre commande</span>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'accueil' %}">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                Commander le Panier
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>

  <section class="news-single nav-arrow-b">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{% url 'commander_panier' %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="mode_paiement">Mode de Paiement :</label>
              <select id="mode_paiement" name="mode_paiement" class="form-control">
                <option value="1">Paiement par carte</option>
                <option value="2">Paiement par orange money</option>
                <option value="3">Paiement sur place une fois livré</option>
              </select>
            </div>
            <button type="submit" class="btn btn-a">Commander le Panier</button>
          </form>
        </div>
      </div>
    </div>
  </section>

</main>

{% endblock %}

KidalApp/templates/KidalApp/conf.html
{% extends "KidalApp/base.html" %}
{% load static %}

{% block content %}

<main id="main">

  <!-- ======= Intro Single ======= -->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">Confirmation</h1>
            <span class="color-text-a">Message reçu</span>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="#">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                Confirmation
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section><!-- End Intro Single-->

  <!-- ======= Confirmation Message ======= -->
  <section class="news-single nav-arrow-b">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="form-comments">
            <div class="title-box-d">
              <h3 class="title-d">Merci {{ user.username }}!</h3>
            </div>
            <p class="lead text-center">Votre message a été reçu avec succès!</p>
            <hr class="my-4">
            <p class="text-center">Vous recevrez bientôt plus d'informations par e-mail.</p>
            <div class="text-center mt-3">
              <a class="btn btn-primary" href="{% url 'accueil' %}" role="button">Retour à l'accueil</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section><!-- End Confirmation Message-->

</main><!-- End #main -->

{% endblock %}

KidalApp/templates/KidalApp/confirmation_commande.html
<!-- KidalApp/confirmation_commande.html -->

{% extends "KidalApp/base.html" %}
{% block content %}
<main id="main">
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">Commande Confirmer</h1>
            <span class="color-text-a">Commande num #{{ commande.id }}</span>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="#">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                Confirmation de Commande
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>

  <section class="news-single nav-arrow-b">
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
          <div class="form-comments">
            <div class="title-box-d">
              <h3 class="title-d">Détails de la commande</h3>
            </div>
            <ul>
              <li>Produit: {{ commande.produit.nom }}</li>
              <li>Description: {{ commande.produit.description }} Kg</li>
              <li>Quantité: {{ commande.quantite }}</li>
              <li>Prix unitaire: {{ commande.produit.prix }} FCFA</li>
              <li>Prix total: {{ prix_total }} FCFA</li>
              <li>Mode de paiement: {{ commande.get_mode_paiement_display }}</li>
            </ul>
            <a href="{% url 'generate_invoice_pdf' commande.id %}" class="btn btn-a">Télécharger la facture</a>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}